### ISSUE TITLE
Provide Edit functionality for Drop Rules

### ISSUE THREAD

**Issue by ricegi** [newrelic-experimental/nr1-drop-rule-explorer#2]
## Summary

Presently the DropRules API does not provide an edit functionality. We'd like to use the delete/create functionality to augment the modification of drop rules using the drop-rule-exporter NR1 App

## Desired Behavior

Customer select a drop rule to edit
Makes necessary edits in the UI
Commits the edit (creating a new drop rule) 
Drop rule is validated for creation
The old Drop rule is deleted

## Possible Solution

TBD - the create then delete workflow is required to ensure we maintain applicability of drop rules that have business senstivity, for example PII elimination 

## Additional context

Internal NR FR

**Comment by marcelschlapfer** [comment]
Also wonder if we can add a "Source" option here to select `Nerdgraph` or `Logging`.  Currently when new rules are created they default to `Nerdgraph` and are not visible in the Logs UI.  When creating a drop filter/rule for Logs it would be nice if it also showed up in the Logs UI.

**Comment by jsbnr** [comment]
I believe the source attribute is  intended to record what UI set the value, so setting it to logging would be violating that.

**Comment by marcelschlapfer** [comment]
I guess I don't see why that's an a issue.  Even when set via Logs UI, it's
just a Nerdgraph API call in the background.  I can create a rule via API
and set source to Logging just fine.  There is nothing restricting that.
The only place where it's not an option is Terraform.  This is a big issue
to folks who want the drop rules they create for Logs to also show up in
the Logs UI.

**Comment by jsbnr** [comment]
This feature was added.
